-- MySQL Script generated by MySQL Workbench
-- 10/25/15 20:41:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema monaco_test
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Schema monaco_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monaco_test` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `monaco_test` ;

-- -----------------------------------------------------
-- Table `monaco_test`.`TAGS_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monaco_test`.`TAGS_REF` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `monaco_test`.`TAGS_REF` (
  `TAG_NAME_ID` INT NOT NULL,
  `TAG_NAME` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `TAG_NAME_ID_UNIQUE` (`TAG_NAME_ID` ASC),
  PRIMARY KEY (`TAG_NAME_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `monaco_test`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monaco_test`.`USER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `monaco_test`.`USER` (
  `userID` INT NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `userTagID` INT NULL,
  `userPass` VARCHAR(45) NOT NULL,
  `creationDate` DATETIME NULL,
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC),
  PRIMARY KEY (`userID`),
  INDEX `userTagID_idx` (`userTagID` ASC),
  CONSTRAINT `USER_userTagID`
    FOREIGN KEY (`userTagID`)
    REFERENCES `monaco_test`.`TAGS_REF` (`TAG_NAME_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `monaco_test`.`PLACE_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monaco_test`.`PLACE_TYPE_REF` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `monaco_test`.`PLACE_TYPE_REF` (
  `PLACE_TYPE_ID` INT NOT NULL,
  `PLACE_TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PLACE_TYPE_ID`),
  UNIQUE INDEX `PLACE_TYPE_ID_UNIQUE` (`PLACE_TYPE_ID` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `monaco_test`.`CITY_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monaco_test`.`CITY_REF` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `monaco_test`.`CITY_REF` (
  `CITY_NAME_ID` INT NOT NULL,
  `CITY_NAME` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `CITY_NAME_ID_UNIQUE` (`CITY_NAME_ID` ASC),
  PRIMARY KEY (`CITY_NAME_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `monaco_test`.`ROUTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monaco_test`.`ROUTE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `monaco_test`.`ROUTE` (
  `routeID` INT NOT NULL,
  `distance` VARCHAR(45) NULL,
  `completionTime` VARCHAR(45) NULL,
  `routeTagID` INT NULL,
  `creationDate` DATETIME NULL,
  `creatorID` INT NULL,
  UNIQUE INDEX `routeID_UNIQUE` (`routeID` ASC),
  PRIMARY KEY (`routeID`),
  INDEX `routeTagId_idx` (`routeTagID` ASC),
  INDEX `creatorID_idx` (`creatorID` ASC),
  CONSTRAINT `ROUTE_routeTagId`
    FOREIGN KEY (`routeTagID`)
    REFERENCES `monaco_test`.`TAGS_REF` (`TAG_NAME_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ROUTE_creatorID`
    FOREIGN KEY (`creatorID`)
    REFERENCES `monaco_test`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `monaco_test`.`PLACE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monaco_test`.`PLACE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `monaco_test`.`PLACE` (
  `placeID` INT NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitute` DOUBLE NOT NULL,
  `cityID` INT NOT NULL,
  `countryID` INT NOT NULL,
  `imageURL` VARCHAR(45) NULL,
  `placeName` VARCHAR(45) NOT NULL,
  `placeAddress` VARCHAR(45) NOT NULL,
  `placeTypeID` INT NULL,
  UNIQUE INDEX `placeID_UNIQUE` (`placeID` ASC),
  PRIMARY KEY (`placeID`),
  INDEX `placeTypeID_idx` (`placeTypeID` ASC),
  INDEX `cityID_idx` (`cityID` ASC),
  CONSTRAINT `PLACE_placeTypeID`
    FOREIGN KEY (`placeTypeID`)
    REFERENCES `monaco_test`.`PLACE_TYPE_REF` (`PLACE_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PLACE_cityID`
    FOREIGN KEY (`cityID`)
    REFERENCES `monaco_test`.`CITY_REF` (`CITY_NAME_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `monaco_test`.`PLACES_IN_ROUTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monaco_test`.`PLACES_IN_ROUTE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `monaco_test`.`PLACES_IN_ROUTE` (
  `routeID` INT NOT NULL,
  `SEQNR` INT NOT NULL,
  `placeID` INT NOT NULL,
  INDEX `placeID_idx` (`placeID` ASC),
  PRIMARY KEY (`routeID`, `SEQNR`),
  CONSTRAINT `PLACEINROUTE_placeID`
    FOREIGN KEY (`placeID`)
    REFERENCES `monaco_test`.`PLACE` (`placeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PLACEINROUTE_routeID`
    FOREIGN KEY (`routeID`)
    REFERENCES `monaco_test`.`ROUTE` (`routeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `monaco_test`.`COMMENT_REVIEW_ON_ROUTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monaco_test`.`COMMENT_REVIEW_ON_ROUTE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `monaco_test`.`COMMENT_REVIEW_ON_ROUTE` (
  `commentOnRouteID` INT NOT NULL,
  `commenterID` INT NOT NULL,
  `routeID` INT NOT NULL,
  `body` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`commentOnRouteID`),
  UNIQUE INDEX `commentOnRouteID_UNIQUE` (`commentOnRouteID` ASC),
  CONSTRAINT `CROR_routeID`
    FOREIGN KEY (`routeID`)
    REFERENCES `monaco_test`.`ROUTE` (`routeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CROR_commenterID`
    FOREIGN KEY (`commenterID`)
    REFERENCES `monaco_test`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `monaco_test`.`COMMENT_REVIEW_ON_PLACE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monaco_test`.`COMMENT_REVIEW_ON_PLACE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `monaco_test`.`COMMENT_REVIEW_ON_PLACE` (
  `commentOnPlaceID` INT NOT NULL,
  `commenterID` INT NOT NULL,
  `placeID` INT NOT NULL,
  `body` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`commentOnPlaceID`),
  UNIQUE INDEX `commentOnPlaceID_UNIQUE` (`commentOnPlaceID` ASC),
  CONSTRAINT `CROP_commenterID`
    FOREIGN KEY (`commenterID`)
    REFERENCES `monaco_test`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CROP_placeID`
    FOREIGN KEY (`placeID`)
    REFERENCES `monaco_test`.`PLACE` (`placeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `monaco_test`.`REVIEW_ON_ROUTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monaco_test`.`REVIEW_ON_ROUTE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `monaco_test`.`REVIEW_ON_ROUTE` (
  `reviewOnRouteID` INT NOT NULL,
  `routeID` INT NOT NULL,
  `creatorID` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `body` VARCHAR(45) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `imageUrl` VARCHAR(45) NULL,
  PRIMARY KEY (`reviewOnRouteID`),
  UNIQUE INDEX `reviewOnRouteID_UNIQUE` (`reviewOnRouteID` ASC),
  INDEX `routeID_idx` (`routeID` ASC),
  CONSTRAINT `ROR_creatorID`
    FOREIGN KEY (`creatorID`)
    REFERENCES `monaco_test`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ROR_routeID`
    FOREIGN KEY (`routeID`)
    REFERENCES `monaco_test`.`ROUTE` (`routeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `monaco_test`.`REVIEW_ON_PLACE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monaco_test`.`REVIEW_ON_PLACE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `monaco_test`.`REVIEW_ON_PLACE` (
  `reviewOnPlaceID` INT NOT NULL,
  `placeID` INT NOT NULL,
  `creatorID` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `body` VARCHAR(45) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `imageUrl` VARCHAR(45) NULL,
  PRIMARY KEY (`reviewOnPlaceID`),
  UNIQUE INDEX `reviewOnPlaceID_UNIQUE` (`reviewOnPlaceID` ASC),
  INDEX `placeID_idx` (`placeID` ASC),
  CONSTRAINT `ROP_creatorID`
    FOREIGN KEY (`creatorID`)
    REFERENCES `monaco_test`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ROP_placeID`
    FOREIGN KEY (`placeID`)
    REFERENCES `monaco_test`.`PLACE` (`placeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;